const { MONGOOSE } = require('../utils/packages');
const { DB_MODELS } = require('../utils/constant');

module.exports = {
    [DB_MODELS.CUSTOMER.MODEL]: MONGOOSE.model(DB_MODELS.CUSTOMER.COLLECTION, require('./schemas/customer.schema'), DB_MODELS.CUSTOMER.COLLECTION),
    [DB_MODELS.CUSTOMER_ADDRESS.MODEL]: MONGOOSE.model(DB_MODELS.CUSTOMER_ADDRESS.COLLECTION, require('./schemas/customerAddress.schema'), DB_MODELS.CUSTOMER_ADDRESS.COLLECTION),
    [DB_MODELS.CUSTOMER_PAYMENT.MODEL]: MONGOOSE.model(DB_MODELS.CUSTOMER_PAYMENT.COLLECTION, require('./schemas/customerPayment.schema'), DB_MODELS.CUSTOMER_PAYMENT.COLLECTION),
    [DB_MODELS.BRAND.MODEL]: MONGOOSE.model(DB_MODELS.BRAND.COLLECTION, require('./schemas/brand.schema'), DB_MODELS.BRAND.COLLECTION),
    [DB_MODELS.DISCOUNT.MODEL]: MONGOOSE.model(DB_MODELS.DISCOUNT.COLLECTION, require('./schemas/discount.schema'), DB_MODELS.DISCOUNT.COLLECTION),
    [DB_MODELS.PRODUCTS.MODEL]: MONGOOSE.model(DB_MODELS.PRODUCTS.COLLECTION, require('./schemas/product.schema'), DB_MODELS.PRODUCTS.COLLECTION),
    [DB_MODELS.PRODUCT_CATEGORY.MODEL]: MONGOOSE.model(DB_MODELS.PRODUCT_CATEGORY.COLLECTION, require('./schemas/productCategory.schema'), DB_MODELS.PRODUCT_CATEGORY.COLLECTION),
    [DB_MODELS.PRODUCT_INVENTORY.MODEL]: MONGOOSE.model(DB_MODELS.PRODUCT_INVENTORY.COLLECTION, require('./schemas/productInventory.schema'), DB_MODELS.PRODUCT_INVENTORY.COLLECTION),
    [DB_MODELS.CART.MODEL]: MONGOOSE.model(DB_MODELS.CART.COLLECTION, require('./schemas/cart.schema'), DB_MODELS.CART.COLLECTION),
    [DB_MODELS.ORDER.MODEL]: MONGOOSE.model(DB_MODELS.ORDER.COLLECTION, require('./schemas/order.schema'), DB_MODELS.ORDER.COLLECTION),
    [DB_MODELS.SHIPMENT.MODEL]: MONGOOSE.model(DB_MODELS.SHIPMENT.COLLECTION, require('./schemas/shipment.schema'), DB_MODELS.SHIPMENT.COLLECTION),
    [DB_MODELS.BANNER.MODEL]: MONGOOSE.model(DB_MODELS.BANNER.COLLECTION, require('./schemas/banner.schema'), DB_MODELS.BANNER.COLLECTION),
    [DB_MODELS.SLIDER.MODEL]: MONGOOSE.model(DB_MODELS.SLIDER.COLLECTION, require('./schemas/sliderPost.schema'), DB_MODELS.SLIDER.COLLECTION),
    [DB_MODELS.NEWS_LETTER_SUBSCRIBE.MODEL]: MONGOOSE.model(DB_MODELS.NEWS_LETTER_SUBSCRIBE.COLLECTION, require('./schemas/subscribe.schema'), DB_MODELS.NEWS_LETTER_SUBSCRIBE.COLLECTION)
};
